/*            Metodo de Newton            */
/*         Rui Alves , 30-10-2017         */

/**********  PARAMETERS  ************/
/*                                  */
/* func - function to analise       */
/* dfunc - function derivative      */
/* guess - first guess value        */
/* num_iter - number of iterations  */


newton(func,dfunc,guess,num_iter):=(
	block([i],
		for i:1 thru num_iter do(
			guess: guess - func(guess)/dfunc(guess),
			print(float(guess))
		)
	)
)$
